#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Entrypoint — Adjusts the container user UID/GID to match the workspace
# volume owner on Linux hosts, so that `cargo build`, `cargo run` etc. write
# files owned by the host user. On macOS / Docker Desktop the volume shows as
# root (UID 0) but is writable by any container UID, so the remap is skipped
# and the "tscrap" user is kept as a normal non-root user.
#
# Also bridges the host dotfiles (nvim config, gitconfig, zshrc, ssh) into the
# effective user's HOME and sets up the forwarded SSH agent socket.

set -eu

USERNAME="${USERNAME:-tscrap}"
USER_UID="${USER_UID:-1000}"
USER_GID="${USER_GID:-1000}"
WORKSPACE="${WORKSPACE:-/workspaces/telescrap-sr}"

# ---- Detect the owner of the workspace mount ---------------------------
if [ -d "$WORKSPACE" ]; then
    MOUNT_UID="$(stat -c '%u' "$WORKSPACE")"
    MOUNT_GID="$(stat -c '%g' "$WORKSPACE")"
else
    MOUNT_UID="$USER_UID"
    MOUNT_GID="$USER_GID"
fi

# ---- (Re)create the user with the detected IDs -------------------------
# Only remap when the workspace is owned by a real (non-root) user, e.g. a
# Linux host. On macOS / Docker Desktop the mount shows as UID 0 but is
# writable regardless, and remapping to UID 0 would wrongly turn the dev user
# into root.
if [ "$MOUNT_UID" -ne 0 ] && [ "$MOUNT_GID" -ne 0 ]; then
    if [ "$MOUNT_GID" -ne "$(id -g "$USERNAME" 2>/dev/null || echo 0)" ]; then
        getent group "$USERNAME" >/dev/null 2>&1 || groupadd "$USERNAME" 2>/dev/null || true
        groupadd --gid "$MOUNT_GID" "$USERNAME" 2>/dev/null || \
            groupmod -o -g "$MOUNT_GID" "$USERNAME" 2>/dev/null || true
    fi

    if [ "$MOUNT_UID" -ne "$(id -u "$USERNAME" 2>/dev/null || echo 0)" ]; then
        usermod -o -u "$MOUNT_UID" -g "$MOUNT_GID" "$USERNAME" 2>/dev/null || true
    fi
fi

# Make sure home directory has correct ownership
chown -R "$(id -u "$USERNAME"):$(id -g "$USERNAME")" "/home/$USERNAME" 2>/dev/null || true

# ---- Make the cargo cache writable by the container user ----------------
# CARGO_HOME is installed system-wide (as root) under /usr/local so the
# binaries are on PATH for everyone. Cargo needs to write to the
# registry/cache when fetching dependencies, so give the container user
# ownership of it. RUSTUP_HOME (the toolchain) only needs to be readable,
# so it stays root-owned (chowning the multi-GB toolchain on every start is
# too slow).
chown -R "$(id -u "$USERNAME"):$(id -g "$USERNAME")" \
    "${CARGO_HOME:-/usr/local/cargo}" 2>/dev/null || true

# Always ensure $USERNAME has passwordless sudo, even if a previous
# usermod/groupmod operation failed or the Dockerfile-created sudoers file
# was lost (e.g. container restart without full rebuild).
if ! grep -qs "^${USERNAME}" /etc/sudoers.d/"${USERNAME}" 2>/dev/null; then
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$USERNAME"
    chmod 440 "/etc/sudoers.d/$USERNAME"
fi

# ---- Bridge host .zshrc (mounted readonly at /home/$USERNAME/.zshrc.host) ----
# Wrap it instead of sourcing directly so we can override host-specific paths
# that are wrong inside the container — most importantly SSH_AUTH_SOCK, which
# the host .zshrc points at the Bitwarden socket (~/.bitwarden-ssh-agent.sock)
# and would otherwise break the forwarded agent at /tmp/ssh-agent.socket.
SOURCE_ZSHRC="/home/$USERNAME/.zshrc.host"
TARGET_ZSHRC="/home/$USERNAME/.zshrc"

if [ -f "$SOURCE_ZSHRC" ] || [ -L "$SOURCE_ZSHRC" ]; then
    if [ ! -e "$TARGET_ZSHRC" ] || grep -qs '^# generated by entrypoint' "$TARGET_ZSHRC"; then
        {
            echo "# generated by entrypoint"
            echo "[ -f \"$SOURCE_ZSHRC\" ] && source \"$SOURCE_ZSHRC\""
            echo "export SSH_AUTH_SOCK=\"/tmp/ssh-agent.socket\""
        } > "$TARGET_ZSHRC"
        chown "$(id -u "$USERNAME"):$(id -g "$USERNAME")" "$TARGET_ZSHRC" 2>/dev/null || true
    fi
fi

# ---- Bridge host .gitconfig (mounted at /home/$USERNAME/.gitconfig.host) ----
# Copy it to a real local file so git reads a stable, non-bind-mounted file.
# This avoids transient read errors from the Docker Desktop bind mount that
# surface as "unknown error occurred while reading the configuration files".
SOURCE_GITCONFIG="/home/$USERNAME/.gitconfig.host"
TARGET_GITCONFIG="/home/$USERNAME/.gitconfig"

if [ -f "$SOURCE_GITCONFIG" ]; then
    cp -f "$SOURCE_GITCONFIG" "$TARGET_GITCONFIG" 2>/dev/null || true
    chown "$(id -u "$USERNAME"):$(id -g "$USERNAME")" "$TARGET_GITCONFIG" 2>/dev/null || true
fi

# ---- Set up SSH for the container user ----------------------------------
# devcontainer.json mounts the host ~/.ssh/config and ~/.ssh/known_hosts at
# /home/$USERNAME/.ssh/.  Prepare the directory so the mounts (and the
# ssh-keyscan in postCreateCommand) have a proper home.
SSH_DIR="/home/$USERNAME/.ssh"
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
chown "$(id -u "$USERNAME"):$(id -g "$USERNAME")" "$SSH_DIR" 2>/dev/null || true

# ---- Make the forwarded SSH agent socket accessible ---------------------
# devcontainer.json forwards the host SSH agent socket into the container at
# /tmp/ssh-agent.socket (via `-v`, since `--mount type=bind` hits a Docker
# Desktop socket-mount bug). Docker Desktop maps it as root:root (0660),
# which the unprivileged runtime user cannot open. Fix ownership so git/ssh
# can reach the agent.
SSH_AGENT_SOCKET="/tmp/ssh-agent.socket"
if [ -S "$SSH_AGENT_SOCKET" ]; then
    chown "$(id -u "$USERNAME"):$(id -g "$USERNAME")" "$SSH_AGENT_SOCKET" 2>/dev/null || \
        chmod 777 "$SSH_AGENT_SOCKET" 2>/dev/null || true
fi

# ---- Drop privileges and execute the requested command -----------------
# We run as root; drop to the adjusted user before exec.
# -E  preserves env vars (RUSTUP_HOME, CARGO_HOME, SSH_AUTH_SOCK…)
# -H  resets HOME to the target user's home.
# If no command is supplied by the runtime, keep the container alive.
if [ "$#" -eq 0 ]; then
    set -- sleep infinity
fi

exec sudo -E -H -u "$USERNAME" "$@"
